version: '3'
services:
  bigpanda:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /public/images:/public/images
    networks:
      - bigpanda

  db:
    build: db/
    networks:
      - bigpanda
  
networks:
  bigpanda:
